Teambuilder.data.types = [
'Cosmic',
'Tech',
'Mutant',
'Skill',
'Science',
'Mystic'
];
Teambuilder.data.effects = TAFFY([
{"code":"bp","text":"+{{value}}% Block Proficiency"},
{"code":"pbc","text":"+{{value}}% Perfect Block Chance"},
{"code":"cr","text":"+{{value}}% Crit Rate"},
{"code":"ar","text":"+{{value}}% Armor"},
{"code":"cd","text":"+{{value}}% Crit Damage"},
{"code":"pg","text":"+{{value}}% Power Gain"},
{"code":"h","text":"+{{value}}% Health"},
{"code":"sc","text":"+{{value}}% Stun Chance"},
{"code":"at","text":"+{{value}}% Attack"}
]);
Teambuilder.data.champions = TAFFY([
{"name":"Abomination","type":"Science","stars":2,"portrait":"portrait_abomination.png"},
{"name":"Abomination","type":"Science","stars":3,"portrait":"portrait_abomination.png"},
{"name":"Abomination","type":"Science","stars":4,"portrait":"portrait_abomination.png"},
{"name":"Ant-Man","type":"Science","stars":2,"portrait":"portrait_antman.png"},
{"name":"Ant-Man","type":"Science","stars":3,"portrait":"portrait_antman.png"},
{"name":"Ant-Man","type":"Science","stars":4,"portrait":"portrait_antman.png"},
{"name":"Black Bolt","type":"Cosmic","stars":2,"portrait":"portrait_black_bolt.png"},
{"name":"Black Bolt","type":"Cosmic","stars":3,"portrait":"portrait_black_bolt.png"},
{"name":"Black Bolt","type":"Cosmic","stars":4,"portrait":"portrait_black_bolt.png"},
{"name":"Black Panther","type":"Skill","stars":1,"portrait":"portrait_black_panther.png"},
{"name":"Black Panther","type":"Skill","stars":2,"portrait":"portrait_black_panther.png"},
{"name":"Black Panther","type":"Skill","stars":3,"portrait":"portrait_black_panther.png"},
{"name":"Black Panther","type":"Skill","stars":4,"portrait":"portrait_black_panther.png"},
{"name":"Black Widow","type":"Skill","stars":2,"portrait":"portrait_black_widow.png"},
{"name":"Black Widow","type":"Skill","stars":3,"portrait":"portrait_black_widow.png"},
{"name":"Black Widow","type":"Skill","stars":4,"portrait":"portrait_black_widow.png"},
{"name":"Captain America","type":"Science","stars":2,"portrait":"portrait_captain_america.png"},
{"name":"Captain America","type":"Science","stars":3,"portrait":"portrait_captain_america.png"},
{"name":"Captain America","type":"Science","stars":4,"portrait":"portrait_captain_america.png"},
{"name":"Captain America WWII","type":"Science","stars":3,"portrait":"portrait_capamerica_wwii.png"},
{"name":"Captain America WWII","type":"Science","stars":4,"portrait":"portrait_capamerica_wwii.png"},
{"name":"Captain Marvel","type":"Cosmic","stars":3,"portrait":"portrait_captain_marvel.png"},
{"name":"Captain Marvel","type":"Cosmic","stars":4,"portrait":"portrait_captain_marvel.png"},
{"name":"Colossus","type":"Mutant","stars":1,"portrait":"portrait_colossus.png"},
{"name":"Colossus","type":"Mutant","stars":2,"portrait":"portrait_colossus.png"},
{"name":"Colossus","type":"Mutant","stars":3,"portrait":"portrait_colossus.png"},
{"name":"Colossus","type":"Mutant","stars":4,"portrait":"portrait_colossus.png"},
{"name":"Cyclops","type":"Mutant","stars":2,"portrait":"portrait_cyclops.png"},
{"name":"Cyclops","type":"Mutant","stars":3,"portrait":"portrait_cyclops.png"},
{"name":"Cyclops","type":"Mutant","stars":4,"portrait":"portrait_cyclops.png"},
{"name":"Daredevil","type":"Skill","stars":3,"portrait":"portrait_daredevil.png"},
{"name":"Daredevil","type":"Skill","stars":4,"portrait":"portrait_daredevil.png"},
{"name":"Deadpool","type":"Mutant","stars":2,"portrait":"portrait_deadpool.png"},
{"name":"Deadpool","type":"Mutant","stars":3,"portrait":"portrait_deadpool.png"},
{"name":"Deadpool","type":"Mutant","stars":4,"portrait":"portrait_deadpool.png"},
{"name":"Dr. Strange","type":"Mystic","stars":3,"portrait":"portrait_doctor_strange.png"},
{"name":"Dr. Strange","type":"Mystic","stars":4,"portrait":"portrait_doctor_strange.png"},
{"name":"Drax","type":"Cosmic","stars":2,"portrait":"portrait_drax.png"},
{"name":"Drax","type":"Cosmic","stars":3,"portrait":"portrait_drax.png"},
{"name":"Drax","type":"Cosmic","stars":4,"portrait":"portrait_drax.png"},
{"name":"Electro","type":"Science","stars":3,"portrait":"portrait_electro.png"},
{"name":"Electro","type":"Science","stars":4,"portrait":"portrait_electro.png"},
{"name":"Gamora","type":"Cosmic","stars":1,"portrait":"portrait_gamora.png"},
{"name":"Gamora","type":"Cosmic","stars":2,"portrait":"portrait_gamora.png"},
{"name":"Gamora","type":"Cosmic","stars":3,"portrait":"portrait_gamora.png"},
{"name":"Gamora","type":"Cosmic","stars":4,"portrait":"portrait_gamora.png"},
{"name":"Hawkeye","type":"Skill","stars":1,"portrait":"portrait_hawkeye.png"},
{"name":"Hawkeye","type":"Skill","stars":2,"portrait":"portrait_hawkeye.png"},
{"name":"Hawkeye","type":"Skill","stars":3,"portrait":"portrait_hawkeye.png"},
{"name":"Hawkeye","type":"Skill","stars":4,"portrait":"portrait_hawkeye.png"},
{"name":"Hulk","type":"Science","stars":1,"portrait":"portrait_hulk.png"},
{"name":"Hulk","type":"Science","stars":2,"portrait":"portrait_hulk.png"},
{"name":"Hulk","type":"Science","stars":3,"portrait":"portrait_hulk.png"},
{"name":"Hulk","type":"Science","stars":4,"portrait":"portrait_hulk.png"},
{"name":"Hulkbuster","type":"Tech","stars":2,"portrait":"portrait_hulkbuster_movie.png"},
{"name":"Hulkbuster","type":"Tech","stars":3,"portrait":"portrait_hulkbuster_movie.png"},
{"name":"Hulkbuster","type":"Tech","stars":4,"portrait":"portrait_hulkbuster_movie.png"},
{"name":"Iron Fist","type":"Mystic","stars":2,"portrait":"portrait_iron_fist.png"},
{"name":"Iron Fist","type":"Mystic","stars":3,"portrait":"portrait_iron_fist.png"},
{"name":"Iron Fist","type":"Mystic","stars":4,"portrait":"portrait_iron_fist.png"},
{"name":"Iron Man","type":"Tech","stars":1,"portrait":"portrait_iron_man.png"},
{"name":"Iron Man","type":"Tech","stars":2,"portrait":"portrait_iron_man.png"},
{"name":"Iron Man","type":"Tech","stars":3,"portrait":"portrait_iron_man.png"},
{"name":"Iron Man","type":"Tech","stars":4,"portrait":"portrait_iron_man.png"},
{"name":"Iron Patriot","type":"Tech","stars":3,"portrait":"portrait_ironpatriot.png"},
{"name":"Iron Patriot","type":"Tech","stars":4,"portrait":"portrait_ironpatriot.png"},
{"name":"Juggernaut","type":"Mystic","stars":1,"portrait":"portrait_juggernaut.png"},
{"name":"Juggernaut","type":"Mystic","stars":2,"portrait":"portrait_juggernaut.png"},
{"name":"Juggernaut","type":"Mystic","stars":3,"portrait":"portrait_juggernaut.png"},
{"name":"Juggernaut","type":"Mystic","stars":4,"portrait":"portrait_juggernaut.png"},
{"name":"Magik","type":"Mystic","stars":2,"portrait":"portrait_magik.png"},
{"name":"Magik","type":"Mystic","stars":3,"portrait":"portrait_magik.png"},
{"name":"Magik","type":"Mystic","stars":4,"portrait":"portrait_magik.png"},
{"name":"Magneto","type":"Mutant","stars":3,"portrait":"portrait_magneto.png"},
{"name":"Magneto","type":"Mutant","stars":4,"portrait":"portrait_magneto.png"},
{"name":"Magneto White","type":"Mutant","stars":3,"portrait":"portrait_magneto_white.png"},
{"name":"Magneto White","type":"Mutant","stars":4,"portrait":"portrait_magneto_white.png"},
{"name":"Ms. Marvel","type":"Cosmic","stars":3,"portrait":"portrait_msmarvel.png"},
{"name":"Ms. Marvel","type":"Cosmic","stars":4,"portrait":"portrait_msmarvel.png"},
{"name":"Punisher","type":"Skill","stars":2,"portrait":"portrait_punisher.png"},
{"name":"Punisher","type":"Skill","stars":3,"portrait":"portrait_punisher.png"},
{"name":"Punisher","type":"Skill","stars":4,"portrait":"portrait_punisher.png"},
{"name":"Rhino","type":"Science","stars":2,"portrait":"portrait_rhino.png"},
{"name":"Rhino","type":"Science","stars":3,"portrait":"portrait_rhino.png"},
{"name":"Rhino","type":"Science","stars":4,"portrait":"portrait_rhino.png"},
{"name":"Rocket Raccoon","type":"Tech","stars":3,"portrait":"portrait_rocket.png"},
{"name":"Rocket Raccoon","type":"Tech","stars":4,"portrait":"portrait_rocket.png"},
{"name":"Ronan","type":"Cosmic","stars":2,"portrait":"portrait_ronan.png"},
{"name":"Ronan","type":"Cosmic","stars":3,"portrait":"portrait_ronan.png"},
{"name":"Ronan","type":"Cosmic","stars":4,"portrait":"portrait_ronan.png"},
{"name":"Scarlet Witch","type":"Mystic","stars":1,"portrait":"portrait_scarlet_witch.png"},
{"name":"Scarlet Witch","type":"Mystic","stars":2,"portrait":"portrait_scarlet_witch.png"},
{"name":"Scarlet Witch","type":"Mystic","stars":3,"portrait":"portrait_scarlet_witch.png"},
{"name":"Scarlet Witch","type":"Mystic","stars":4,"portrait":"portrait_scarlet_witch.png"},
{"name":"Spider-Man","type":"Science","stars":1,"portrait":"portrait_spider_man.png"},
{"name":"Spider-Man","type":"Science","stars":2,"portrait":"portrait_spider_man.png"},
{"name":"Spider-Man","type":"Science","stars":3,"portrait":"portrait_spider_man.png"},
{"name":"Spider-Man","type":"Science","stars":4,"portrait":"portrait_spider_man.png"},
{"name":"Star-Lord","type":"Tech","stars":2,"portrait":"portrait_star_lord.png"},
{"name":"Star-Lord","type":"Tech","stars":3,"portrait":"portrait_star_lord.png"},
{"name":"Star-Lord","type":"Tech","stars":4,"portrait":"portrait_star_lord.png"},
{"name":"Storm","type":"Mutant","stars":2,"portrait":"portrait_storm.png"},
{"name":"Storm","type":"Mutant","stars":3,"portrait":"portrait_storm.png"},
{"name":"Storm","type":"Mutant","stars":4,"portrait":"portrait_storm.png"},
{"name":"Super. Iron Man","type":"Cosmic","stars":2,"portrait":"portrait_ironman_superior.png"},
{"name":"Super. Iron Man","type":"Cosmic","stars":3,"portrait":"portrait_ironman_superior.png"},
{"name":"Super. Iron Man","type":"Cosmic","stars":4,"portrait":"portrait_ironman_superior.png"},
{"name":"The Vision","type":"Tech","stars":2,"portrait":"portrait_vision_movie.png"},
{"name":"The Vision","type":"Tech","stars":3,"portrait":"portrait_vision_movie.png"},
{"name":"The Vision","type":"Tech","stars":4,"portrait":"portrait_vision_movie.png"},
{"name":"Thor","type":"Cosmic","stars":2,"portrait":"portrait_thor.png"},
{"name":"Thor","type":"Cosmic","stars":3,"portrait":"portrait_thor.png"},
{"name":"Thor","type":"Cosmic","stars":4,"portrait":"portrait_thor.png"},
{"name":"Ultron Prime","type":"Tech","stars":3,"portrait":"portrait_ultron_prime.png"},
{"name":"Ultron Prime","type":"Tech","stars":4,"portrait":"portrait_ultron_prime.png"},
{"name":"Unst. Colossus","type":"Mystic","stars":2,"portrait":"portrait_colossus_unstoppable.png"},
{"name":"Unst. Colossus","type":"Mystic","stars":3,"portrait":"portrait_colossus_unstoppable.png"},
{"name":"Unst. Colossus","type":"Mystic","stars":4,"portrait":"portrait_colossus_unstoppable.png"},
{"name":"Vision","type":"Tech","stars":1,"portrait":"portrait_vision.png"},
{"name":"Vision","type":"Tech","stars":2,"portrait":"portrait_vision.png"},
{"name":"Vision","type":"Tech","stars":3,"portrait":"portrait_vision.png"},
{"name":"Vision","type":"Tech","stars":4,"portrait":"portrait_vision.png"},
{"name":"War Machine","type":"Mutant","stars":3,"portrait":"portrait_warmachine.png"},
{"name":"War Machine","type":"Mutant","stars":4,"portrait":"portrait_warmachine.png"},
{"name":"Winter Soldier","type":"Skill","stars":2,"portrait":"portrait_winter_soldier.png"},
{"name":"Winter Soldier","type":"Skill","stars":3,"portrait":"portrait_winter_soldier.png"},
{"name":"Winter Soldier","type":"Skill","stars":4,"portrait":"portrait_winter_soldier.png"},
{"name":"Wolverine","type":"Mutant","stars":1,"portrait":"portrait_wolverine.png"},
{"name":"Wolverine","type":"Mutant","stars":2,"portrait":"portrait_wolverine.png"},
{"name":"Wolverine","type":"Mutant","stars":3,"portrait":"portrait_wolverine.png"},
{"name":"Wolverine","type":"Mutant","stars":4,"portrait":"portrait_wolverine.png"},
{"name":"Yellowjacket","type":"Science","stars":2,"portrait":"portrait_yellowjacket.png"},
{"name":"Yellowjacket","type":"Science","stars":3,"portrait":"portrait_yellowjacket.png"},
{"name":"Yellowjacket","type":"Science","stars":4,"portrait":"portrait_yellowjacket.png"}
]);
Teambuilder.data.synergies = TAFFY([
//2
{	"from":"Abomination",		"stars":2,	"to":"Rhino",			"effect":"ar",	"value":4	},
{	"from":"Ant-Man",			"stars":2,	"to":"Yellowjacket",	"effect":"at",	"value":5	},
{	"from":"Ant-Man",			"stars":2,	"to":"Spider-Man",		"effect":"pbc",	"value":3	},
{	"from":"Black Bolt",		"stars":2,	"to":"Cyclops",			"effect":"bp",	"value":10	},
{	"from":"Black Panther",		"stars":2,	"to":"Iron Fist",		"effect":"cd",	"value":15	},
{	"from":"Black Widow",		"stars":2,	"to":"Captain Marvel",	"effect":"ar",	"value":4	},
{	"from":"Black Widow",		"stars":2,	"to":"Winter Soldier",	"effect":"pg",	"value":3	},
{	"from":"Captain America",	"stars":2,	"to":"Spider-Man",		"effect":"ar",	"value":4	},
{	"from":"Captain America",	"stars":2,	"to":"Super. Iron Man",	"effect":"cr",	"value":5	},
{	"from":"Captain America",	"stars":2,	"to":"Iron Man",		"effect":"pbc",	"value":3	},
{	"from":"Colossus",			"stars":2,	"to":"Juggernaut",		"effect":"cr",	"value":5	},
{	"from":"Cyclops",			"stars":2,	"to":"Wolverine",		"effect":"cd",	"value":15	},
{	"from":"Deadpool",			"stars":2,	"to":"Rhino",			"effect":"cr",	"value":5	},
{	"from":"Deadpool",			"stars":2,	"to":"Wolverine",		"effect":"cr",	"value":7	},
{	"from":"Deadpool",			"stars":2,	"to":"Punisher",		"effect":"pbc",	"value":3	},
{	"from":"Drax",				"stars":2,	"to":"Star-Lord",		"effect":"pbc",	"value":3	},
{	"from":"Drax",				"stars":2,	"to":"Gamora",			"effect":"cd",	"value":15	},
{	"from":"Gamora",			"stars":2,	"to":"Star-Lord",		"effect":"ar",	"value":4	},
{	"from":"Hawkeye",			"stars":2,	"to":"Scarlet Witch",	"effect":"pg",	"value":3	},
{	"from":"Hulk",				"stars":2,	"to":"Thor",			"effect":"cd",	"value":15	},
{	"from":"Hulkbuster",		"stars":2,	"to":"Hulk",			"effect":"cd",	"value":15	},
{	"from":"Iron Fist",			"stars":2,	"to":"Black Panther",	"effect":"ar",	"value":4	},
{	"from":"Iron Man",			"stars":2,	"to":"Thor",			"effect":"pbc",	"value":3	},
{	"from":"Juggernaut",		"stars":2,	"to":"Colossus",		"effect":"cr",	"value":5	},
{	"from":"Magik",				"stars":2,	"to":"Colossus",		"effect":"h",	"value":4	},
{	"from":"Punisher",			"stars":2,	"to":"Spider-Man",		"effect":"cd",	"value":15	},
{	"from":"Rhino",				"stars":2,	"to":"Spider-Man",		"effect":"cr",	"value":5	},
{	"from":"Rhino",				"stars":2,	"to":"Abomination",		"effect":"ar",	"value":4	},
{	"from":"Ronan",				"stars":2,	"to":"Black Bolt",		"effect":"cd",	"value":15	},
{	"from":"Scarlet Witch",		"stars":2,	"to":"Captain Marvel",	"effect":"ar",	"value":4	},
{	"from":"Spider-Man",		"stars":2,	"to":"Wolverine",		"effect":"h",	"value":5	},
{	"from":"Spider-Man",		"stars":2,	"to":"Hawkeye",			"effect":"ar",	"value":5	},
{	"from":"Star-Lord",			"stars":2,	"to":"Rocket Raccoon",	"effect":"ar",	"value":4	},
{	"from":"Star-Lord",			"stars":2,	"to":"Drax",			"effect":"pbc",	"value":3	},
{	"from":"Storm",				"stars":2,	"to":"Black Panther",	"effect":"pg",	"value":3	},
{	"from":"Super. Iron Man",	"stars":2,	"to":"Captain America",	"effect":"cr",	"value":5	},
{	"from":"Super. Iron Man",	"stars":2,	"to":"Thor",			"effect":"pbc",	"value":3	},
{	"from":"The Vision",		"stars":2,	"to":"Iron Man",		"effect":"ar",	"value":4	},
{	"from":"The Vision",		"stars":2,	"to":"Scarlet Witch",	"effect":"pbc",	"value":3	},
{	"from":"Thor",				"stars":2,	"to":"Dr. Strange",		"effect":"ar",	"value":4	},
{	"from":"Thor",				"stars":2,	"to":"Iron Man",		"effect":"ar",	"value":4	},
{	"from":"Unst. Colossus",	"stars":2,	"to":"Magik",			"effect":"h",	"value":5	},
{	"from":"Unst. Colossus",	"stars":2,	"to":"Juggernaut",		"effect":"cd",	"value":20	},
{	"from":"Vision",			"stars":2,	"to":"Scarlet Witch",	"effect":"pg",	"value":3	},
{	"from":"Vision",			"stars":2,	"to":"Iron Man",		"effect":"pbc",	"value":3	},
{	"from":"Wolverine",			"stars":2,	"to":"Cyclops",			"effect":"cd",	"value":15	},
{	"from":"Winter Soldier",	"stars":2,	"to":"Wolverine",		"effect":"ar",	"value":4	},
{	"from":"Winter Soldier",	"stars":2,	"to":"Captain America",	"effect":"pbc",	"value":3	},
{	"from":"Yellowjacket",		"stars":2,	"to":"Ant-Man",			"effect":"at",	"value":4	},
//3
{	"from":"Abomination",		"stars":3,	"to":"Hulk",			"effect":"at",	"value":4	},
{	"from":"Abomination",		"stars":3,	"to":"Rhino",			"effect":"ar",	"value":5	},
{	"from":"Ant-Man",			"stars":4,	"to":"Yellowjacket",	"effect":"at",	"value":5	},
{	"from":"Ant-Man",			"stars":4,	"to":"Spider-Man",		"effect":"pbc",	"value":4	},
{	"from":"Ant-Man",			"stars":4,	"to":"Iron Man",		"effect":"pbc",	"value":4	},
{	"from":"Black Bolt",		"stars":3,	"to":"Ronan",			"effect":"at",	"value":4	},
{	"from":"Black Bolt",		"stars":3,	"to":"Spider-Man",		"effect":"ar",	"value":5	},
{	"from":"Black Bolt",		"stars":3,	"to":"Cyclops",			"effect":"bp",	"value":15	},
{	"from":"Black Bolt",		"stars":3,	"to":"Hulk",			"effect":"cd",	"value":20	},
{	"from":"Black Panther",		"stars":3,	"to":"Deadpool",		"effect":"cr",	"value":6	},
{	"from":"Black Panther",		"stars":3,	"to":"Storm",			"effect":"pg",	"value":4	},
{	"from":"Black Panther",		"stars":3,	"to":"Iron Fist",		"effect":"cd",	"value":20	},
{	"from":"Black Widow",		"stars":3,	"to":"Captain Marvel",	"effect":"ar",	"value":5	},
{	"from":"Black Widow",		"stars":3,	"to":"Winter Soldier",	"effect":"pg",	"value":4	},
{	"from":"Black Widow",		"stars":3,	"to":"Hawkeye",			"effect":"pg",	"value":4	},
{	"from":"Black Widow",		"stars":3,	"to":"Hulk",			"effect":"sc",	"value":20	},
{	"from":"Captain America",	"stars":3,	"to":"Spider-Man",		"effect":"ar",	"value":5	},
{	"from":"Captain America",	"stars":3,	"to":"Winter Soldier",	"effect":"ar",	"value":5	},
{	"from":"Captain America",	"stars":3,	"to":"Super. Iron Man",	"effect":"cr",	"value":6	},
{	"from":"Captain America",	"stars":3,	"to":"Iron Man",		"effect":"pbc",	"value":4	},
{	"from":"Captain America WWII",	"stars":3,	"to":"Winter Soldier",	"effect":"ar",	"value":5	},
{	"from":"Captain America WWII",	"stars":3,	"to":"Wolverine",	"effect":"ar",	"value":5	},
{	"from":"Captain Marvel",	"stars":3,	"to":"Captain America",	"effect":"ar",	"value":5	},
{	"from":"Captain Marvel",	"stars":3,	"to":"Gamora",			"effect":"ar",	"value":5	},
{	"from":"Captain Marvel",	"stars":3,	"to":"Iron Man",		"effect":"ar",	"value":5	},
{	"from":"Colossus",			"stars":3,	"to":"Wolverine",		"effect":"ar",	"value":5	},
{	"from":"Colossus",			"stars":3,	"to":"Juggernaut",		"effect":"cr",	"value":6	},
{	"from":"Colossus",			"stars":3,	"to":"Magik",			"effect":"h",	"value":4	},
{	"from":"Cyclops",			"stars":3,	"to":"Wolverine",		"effect":"cd",	"value":20	},
{	"from":"Cyclops",			"stars":3,	"to":"Magneto",			"effect":"at",	"value":4	},
{	"from":"Daredevil",			"stars":3,	"to":"Super. Iron Man",	"effect":"cd",	"value":20	},
{	"from":"Daredevil",			"stars":3,	"to":"Black Widow",		"effect":"pg",	"value":4	},
{	"from":"Deadpool",			"stars":3,	"to":"Rhino",			"effect":"cr",	"value":6	},
{	"from":"Deadpool",			"stars":3,	"to":"Wolverine",		"effect":"h",	"value":4	},
{	"from":"Deadpool",			"stars":3,	"to":"Punisher",		"effect":"pbc",	"value":4	},
{	"from":"Dr. Strange",		"stars":3,	"to":"Thor",			"effect":"ar",	"value":5	},
{	"from":"Dr. Strange",		"stars":3,	"to":"Spider-Man",		"effect":"ar",	"value":5	},
{	"from":"Dr. Strange",		"stars":3,	"to":"Scarlet Witch",	"effect":"bp",	"value":15	},
{	"from":"Dr. Strange",		"stars":3,	"to":"Black Bolt",		"effect":"pbc",	"value":4	},
{	"from":"Drax",				"stars":3,	"to":"Star-Lord",		"effect":"pbc",	"value":4	},
{	"from":"Drax",				"stars":3,	"to":"Gamora",			"effect":"cd",	"value":20	},
{	"from":"Electro",			"stars":3,	"to":"Spider-Man",		"effect":"at",	"value":4	},
{	"from":"Electro",			"stars":3,	"to":"Rhino",			"effect":"ar",	"value":5	},
{	"from":"Gamora",			"stars":3,	"to":"Star-Lord",		"effect":"ar",	"value":5	},
{	"from":"Gamora",			"stars":3,	"to":"Drax",			"effect":"cd",	"value":20	},
{	"from":"Hawkeye",			"stars":3,	"to":"Iron Man",		"effect":"ar",	"value":5	},
{	"from":"Hawkeye",			"stars":3,	"to":"Scarlet Witch",	"effect":"pg",	"value":4	},
{	"from":"Hulk",				"stars":3,	"to":"Abomination",		"effect":"cr",	"value":6	},
{	"from":"Hulk",				"stars":3,	"to":"Hawkeye",			"effect":"ar",	"value":5	},
{	"from":"Hulk",				"stars":3,	"to":"Thor",			"effect":"cd",	"value":20	},
{	"from":"Hulkbuster",		"stars":3,	"to":"Iron Man",		"effect":"h",	"value":4	},
{	"from":"Hulkbuster",		"stars":3,	"to":"Super. Iron Man",	"effect":"h",	"value":4	},
{	"from":"Hulkbuster",		"stars":3,	"to":"Hulk",			"effect":"cd",	"value":20	},
{	"from":"Iron Fist",			"stars":3,	"to":"Dr. Strange",		"effect":"ar",	"value":5	},
{	"from":"Iron Fist",			"stars":3,	"to":"Black Panther",	"effect":"ar",	"value":5	},
{	"from":"Iron Man",			"stars":3,	"to":"Captain America",	"effect":"ar",	"value":5	},
{	"from":"Iron Man",			"stars":3,	"to":"Thor",			"effect":"pbc",	"value":4	},
{	"from":"Iron Patriot",		"stars":3,	"to":"Iron Man",		"effect":"ar",	"value":5	},
{	"from":"Iron Patriot",		"stars":3,	"to":"Spiderman",		"effect":"cr",	"value":6	},
{	"from":"Iron Patriot",		"stars":3,	"to":"Captain America",	"effect":"cd",	"value":20	},
{	"from":"Juggernaut",		"stars":3,	"to":"Dr. Strange",		"effect":"at",	"value":4	},
{	"from":"Juggernaut",		"stars":3,	"to":"Colossus",		"effect":"cr",	"value":6	},
{	"from":"Juggernaut",		"stars":3,	"to":"Hulk",			"effect":"cr",	"value":6	},
{	"from":"Magik",				"stars":3,	"to":"Colossus",		"effect":"h",	"value":4	},
{	"from":"Magik",				"stars":3,	"to":"Storm",			"effect":"ar",	"value":5	},
{	"from":"Magik",				"stars":3,	"to":"Cyclops",			"effect":"pbc",	"value":4	},
{	"from":"Magneto",			"stars":3,	"to":"Vision",			"effect":"cr",	"value":6	},
{	"from":"Magneto",			"stars":3,	"to":"Storm",			"effect":"cd",	"value":20	},
{	"from":"Magneto White",		"stars":3,	"to":"Cyclops",			"effect":"pbc",	"value":4	},
{	"from":"Magneto White",		"stars":3,	"to":"Magik",			"effect":"pbc",	"value":4	},
{	"from":"Magneto White",		"stars":3,	"to":"Storm",			"effect":"cd",	"value":20	},
{	"from":"Ms. Marvel",		"stars":3,	"to":"Captain America",	"effect":"ar",	"value":5	},
{	"from":"Ms. Marvel",		"stars":3,	"to":"Iron Man",		"effect":"pbc",	"value":4	},
{	"from":"Ms. Marvel",		"stars":3,	"to":"Thor",			"effect":"pbc",	"value":4	},
{	"from":"Ms. Marvel",		"stars":3,	"to":"Hulk",			"effect":"pbc",	"value":4	},
{	"from":"Punisher",			"stars":3,	"to":"Rhino",			"effect":"pbc",	"value":4	},
{	"from":"Punisher",			"stars":3,	"to":"Spider-Man",		"effect":"cd",	"value":20	},
{	"from":"Rhino",				"stars":3,	"to":"Abomination",		"effect":"ar",	"value":5	},
{	"from":"Rhino",				"stars":3,	"to":"Spider-Man",		"effect":"cr",	"value":6	},
{	"from":"Rhino",				"stars":3,	"to":"Electro",			"effect":"pbc",	"value":4	},
{	"from":"Rocket Raccoon",	"stars":3,	"to":"Ronan",			"effect":"cr",	"value":6	},
{	"from":"Rocket Raccoon",	"stars":3,	"to":"Star-Lord",		"effect":"ar",	"value":5	},
{	"from":"Rocket Raccoon",	"stars":3,	"to":"Gamora",			"effect":"pbc",	"value":4	},
{	"from":"Rocket Raccoon",	"stars":3,	"to":"Drax",			"effect":"pbc",	"value":4	},
{	"from":"Ronan",				"stars":3,	"to":"Iron Man",		"effect":"cr",	"value":6	},
{	"from":"Ronan",				"stars":3,	"to":"Black Bolt",		"effect":"cd",	"value":20	},
{	"from":"Ronan",				"stars":3,	"to":"Gamora",			"effect":"cd",	"value":20	},
{	"from":"Scarlet Witch",		"stars":3,	"to":"Captain Marvel",	"effect":"ar",	"value":5	},
{	"from":"Scarlet Witch",		"stars":3,	"to":"Vision",			"effect":"pg",	"value":4	},
{	"from":"Spider-Man",		"stars":3,	"to":"Hawkeye",			"effect":"at",	"value":4	},
{	"from":"Spider-Man",		"stars":3,	"to":"Electro",			"effect":"cr",	"value":6	},
{	"from":"Spider-Man",		"stars":3,	"to":"Wolverine",		"effect":"h",	"value":5	},
{	"from":"Spider-Man",		"stars":3,	"to":"Captain America",	"effect":"ar",	"value":5	},
{	"from":"Star-Lord",			"stars":3,	"to":"Rocket Raccoon",	"effect":"ar",	"value":5	},
{	"from":"Star-Lord",			"stars":3,	"to":"Drax",			"effect":"pbc",	"value":4	},
{	"from":"Star-Lord",			"stars":3,	"to":"Gamora",			"effect":"pbc",	"value":4	},
{	"from":"Storm",				"stars":3,	"to":"Magik",			"effect":"ar",	"value":6	},
{	"from":"Storm",				"stars":3,	"to":"Black Panther",	"effect":"pg",	"value":4	},
{	"from":"Storm",				"stars":3,	"to":"Cyclops",			"effect":"pbc",	"value":4	},
{	"from":"Storm",				"stars":3,	"to":"Magneto",			"effect":"cr",	"value":6	},
{	"from":"Super. Iron Man",	"stars":3,	"to":"Captain America",	"effect":"cr",	"value":6	},
{	"from":"Super. Iron Man",	"stars":3,	"to":"Daredevil",		"effect":"cd",	"value":20	},
{	"from":"Super. Iron Man",	"stars":3,	"to":"Thor",			"effect":"pbc",	"value":4	},
{	"from":"The Vision",		"stars":3,	"to":"Iron Man",		"effect":"h",	"value":5	},
{	"from":"The Vision",		"stars":3,	"to":"Scarlet Witch",	"effect":"pbc",	"value":4	},
{	"from":"The Vision",		"stars":3,	"to":"Ultron Prime",	"effect":"at",	"value":4	},
{	"from":"Thor",				"stars":3,	"to":"Dr. Strange",		"effect":"ar",	"value":5	},
{	"from":"Thor",				"stars":3,	"to":"Iron Man",		"effect":"ar",	"value":5	},
{	"from":"Thor",				"stars":3,	"to":"Juggernaut",		"effect":"cr",	"value":6	},
{	"from":"Ultron Prime",		"stars":3,	"to":"Iron Man",		"effect":"h",	"value":5	},
{	"from":"Ultron Prime",		"stars":3,	"to":"Scarlet Witch",	"effect":"ar",	"value":5	},
{	"from":"Unst. Colossus",	"stars":3,	"to":"Wolverine",		"effect":"ar",	"value":5	},
{	"from":"Unst. Colossus",	"stars":3,	"to":"Magik",			"effect":"h",	"value":5	},
{	"from":"Unst. Colossus",	"stars":3,	"to":"Cyclops",			"effect":"pbc",	"value":4	},
{	"from":"Unst. Colossus",	"stars":3,	"to":"Juggernaut",		"effect":"cd",	"value":20	},
{	"from":"Vision",			"stars":3,	"to":"Scarlet Witch",	"effect":"pg",	"value":4	},
{	"from":"Vision",			"stars":3,	"to":"Iron Man",		"effect":"pbc",	"value":4	},
{	"from":"War Machine",		"stars":3,	"to":"Hulkbuster",		"effect":"ar",	"value":5	},
{	"from":"War Machine",		"stars":3,	"to":"Hawkeye",			"effect":"bp",	"value":15	},
{	"from":"War Machine",		"stars":3,	"to":"Black Widow",		"effect":"pbc",	"value":4	},
{	"from":"Winter Soldier",	"stars":3,	"to":"Wolverine",		"effect":"ar",	"value":5	},
{	"from":"Winter Soldier",	"stars":3,	"to":"Captain America",	"effect":"pbc",	"value":4	},
{	"from":"Wolverine",			"stars":3,	"to":"Captain America",	"effect":"ar",	"value":5	},
{	"from":"Wolverine",			"stars":3,	"to":"Cyclops",			"effect":"cd",	"value":20	},
{	"from":"Wolverine",			"stars":3,	"to":"Magneto",			"effect":"cr",	"value":6	},
{	"from":"Yellowjacket",		"stars":3,	"to":"Ant-Man",			"effect":"at",	"value":5	},
//4
{	"from":"Abomination",		"stars":4,	"to":"Hulk",			"effect":"at",	"value":5	},
{	"from":"Abomination",		"stars":4,	"to":"Rhino",			"effect":"ar",	"value":6	},
{	"from":"Ant-Man",			"stars":4,	"to":"Hulk",			"effect":"ar",	"value":6	},
{	"from":"Ant-Man",			"stars":4,	"to":"Yellowjacket",	"effect":"at",	"value":6	},
{	"from":"Ant-Man",			"stars":4,	"to":"Spider-Man",		"effect":"pbc",	"value":5	},
{	"from":"Ant-Man",			"stars":4,	"to":"Iron Man",		"effect":"pbc",	"value":5	},
{	"from":"Black Bolt",		"stars":4,	"to":"Ronan",			"effect":"at",	"value":5	},
{	"from":"Black Bolt",		"stars":4,	"to":"Spider-Man",		"effect":"ar",	"value":6	},
{	"from":"Black Bolt",		"stars":4,	"to":"Cyclops",			"effect":"bp",	"value":20	},
{	"from":"Black Bolt",		"stars":4,	"to":"Hulk",			"effect":"cd",	"value":25	},
{	"from":"Black Panther",		"stars":4,	"to":"Deadpool",		"effect":"cr",	"value":7	},
{	"from":"Black Panther",		"stars":4,	"to":"Storm",			"effect":"pg",	"value":5	},
{	"from":"Black Panther",		"stars":4,	"to":"Iron Fist",		"effect":"cd",	"value":25	},
{	"from":"Black Widow",		"stars":4,	"to":"Captain Marvel",	"effect":"ar",	"value":5	},
{	"from":"Black Widow",		"stars":4,	"to":"Winter Soldier",	"effect":"pg",	"value":4	},
{	"from":"Black Widow",		"stars":4,	"to":"Hawkeye",			"effect":"pg",	"value":4	},
{	"from":"Black Widow",		"stars":4,	"to":"Hulk",			"effect":"sc",	"value":20	},
{	"from":"Captain America",	"stars":4,	"to":"Spider-Man",		"effect":"ar",	"value":6	},
{	"from":"Captain America",	"stars":4,	"to":"Winter Soldier",	"effect":"ar",	"value":6	},
{	"from":"Captain America",	"stars":4,	"to":"Super. Iron Man",	"effect":"cr",	"value":7	},
{	"from":"Captain America",	"stars":4,	"to":"Iron Man",		"effect":"pbc",	"value":5	},
{	"from":"Captain America WWII",	"stars":4,	"to":"Winter Soldier",	"effect":"ar",	"value":6	},
{	"from":"Captain America WWII",	"stars":4,	"to":"Wolverine",	"effect":"ar",	"value":6	},
{	"from":"Captain Marvel",	"stars":4,	"to":"Captain America",	"effect":"ar",	"value":6	},
{	"from":"Captain Marvel",	"stars":4,	"to":"Gamora",			"effect":"ar",	"value":6	},
{	"from":"Captain Marvel",	"stars":4,	"to":"Iron Man",		"effect":"ar",	"value":6	},
{	"from":"Captain Marvel",	"stars":4,	"to":"Wolverine",		"effect":"pg",	"value":5	},
{	"from":"Colossus",			"stars":4,	"to":"Wolverine",		"effect":"ar",	"value":6	},
{	"from":"Colossus",			"stars":4,	"to":"Juggernaut",		"effect":"cr",	"value":7	},
{	"from":"Colossus",			"stars":4,	"to":"Magik",			"effect":"h",	"value":5	},
{	"from":"Cyclops",			"stars":4,	"to":"Wolverine",		"effect":"cd",	"value":25	},
{	"from":"Cyclops",			"stars":4,	"to":"Magneto",			"effect":"at",	"value":5	},
{	"from":"Daredevil",			"stars":4,	"to":"Super. Iron Man",	"effect":"cd",	"value":25	},
{	"from":"Daredevil",			"stars":4,	"to":"Black Widow",		"effect":"pg",	"value":5	},
{	"from":"Deadpool",			"stars":4,	"to":"Rhino",			"effect":"cr",	"value":7	},
{	"from":"Deadpool",			"stars":4,	"to":"Wolverine",		"effect":"h",	"value":5	},
{	"from":"Deadpool",			"stars":4,	"to":"Punisher",		"effect":"pbc",	"value":5	},
{	"from":"Dr. Strange",		"stars":4,	"to":"Thor",			"effect":"ar",	"value":6	},
{	"from":"Dr. Strange",		"stars":4,	"to":"Spider-Man",		"effect":"ar",	"value":6	},
{	"from":"Dr. Strange",		"stars":4,	"to":"Scarlet Witch",	"effect":"bp",	"value":20	},
{	"from":"Dr. Strange",		"stars":4,	"to":"Black Bolt",		"effect":"pbc",	"value":5	},
{	"from":"Drax",				"stars":4,	"to":"Star-Lord",		"effect":"pbc",	"value":5	},
{	"from":"Drax",				"stars":4,	"to":"Gamora",			"effect":"cd",	"value":25	},
{	"from":"Electro",			"stars":4,	"to":"Spider-Man",		"effect":"at",	"value":5	},
{	"from":"Electro",			"stars":4,	"to":"Rhino",			"effect":"ar",	"value":6	},
{	"from":"Gamora",			"stars":4,	"to":"Star-Lord",		"effect":"ar",	"value":6	},
{	"from":"Gamora",			"stars":4,	"to":"Drax",			"effect":"cd",	"value":25	},
{	"from":"Hawkeye",			"stars":4,	"to":"Hulk",			"effect":"ar",	"value":6	},
{	"from":"Hawkeye",			"stars":4,	"to":"Iron Man",		"effect":"ar",	"value":6	},
{	"from":"Hawkeye",			"stars":4,	"to":"Scarlet Witch",	"effect":"pg",	"value":5	},
{	"from":"Hulk",				"stars":4,	"to":"Abomination",		"effect":"cr",	"value":7	},
{	"from":"Hulk",				"stars":4,	"to":"Hawkeye",			"effect":"ar",	"value":6	},
{	"from":"Hulk",				"stars":4,	"to":"Thor",			"effect":"cd",	"value":25	},
{	"from":"Hulkbuster",		"stars":4,	"to":"Iron Man",		"effect":"h",	"value":5	},
{	"from":"Hulkbuster",		"stars":4,	"to":"Super. Iron Man",	"effect":"h",	"value":5	},
{	"from":"Hulkbuster",		"stars":4,	"to":"Hulk",			"effect":"cd",	"value":25	},
{	"from":"Iron Fist",			"stars":4,	"to":"Dr. Strange",		"effect":"ar",	"value":5	},
{	"from":"Iron Fist",			"stars":4,	"to":"Black Panther",	"effect":"ar",	"value":6	},
{	"from":"Iron Man",			"stars":4,	"to":"Captain America",	"effect":"ar",	"value":6	},
{	"from":"Iron Man",			"stars":4,	"to":"Thor",			"effect":"pbc",	"value":5	},
{	"from":"Iron Patriot",		"stars":3,	"to":"Iron Man",		"effect":"ar",	"value":6	},
{	"from":"Iron Patriot",		"stars":3,	"to":"Spiderman",		"effect":"cr",	"value":7	},
{	"from":"Iron Patriot",		"stars":3,	"to":"Captain America",	"effect":"cd",	"value":25	},
{	"from":"Juggernaut",		"stars":4,	"to":"Dr. Strange",		"effect":"at",	"value":5	},
{	"from":"Juggernaut",		"stars":4,	"to":"Colossus",		"effect":"cr",	"value":7	},
{	"from":"Juggernaut",		"stars":4,	"to":"Hulk",			"effect":"cr",	"value":7	},
{	"from":"Magik",				"stars":4,	"to":"Juggernaut",		"effect":"cr",	"value":7	},
{	"from":"Magik",				"stars":4,	"to":"Colossus",		"effect":"h",	"value":6	},
{	"from":"Magik",				"stars":4,	"to":"Storm",			"effect":"ar",	"value":6	},
{	"from":"Magik",				"stars":4,	"to":"Cyclops",			"effect":"pbc",	"value":5	},
{	"from":"Magneto",			"stars":4,	"to":"Vision",			"effect":"cr",	"value":7	},
{	"from":"Magneto",			"stars":4,	"to":"Storm",			"effect":"cd",	"value":25	},
{	"from":"Magneto White",		"stars":4,	"to":"Cyclops",			"effect":"pbc",	"value":5	},
{	"from":"Magneto White",		"stars":4,	"to":"Magik",			"effect":"pbc",	"value":5	},
{	"from":"Magneto White",		"stars":4,	"to":"Storm",			"effect":"cd",	"value":25	},
{	"from":"Ms. Marvel",		"stars":4,	"to":"Captain America",	"effect":"ar",	"value":6	},
{	"from":"Ms. Marvel",		"stars":4,	"to":"Iron Man",		"effect":"pbc",	"value":5	},
{	"from":"Ms. Marvel",		"stars":4,	"to":"Thor",			"effect":"pbc",	"value":5	},
{	"from":"Ms. Marvel",		"stars":4,	"to":"Hulk",			"effect":"pbc",	"value":5	},
{	"from":"Punisher",			"stars":4,	"to":"Rhino",			"effect":"pbc",	"value":5	},
{	"from":"Punisher",			"stars":4,	"to":"Spider-Man",		"effect":"cd",	"value":25	},
{	"from":"Rhino",				"stars":4,	"to":"Abomination",		"effect":"ar",	"value":6	},
{	"from":"Rhino",				"stars":4,	"to":"Spider-Man",		"effect":"cr",	"value":7	},
{	"from":"Rhino",				"stars":4,	"to":"Electro",			"effect":"pbc",	"value":5	},
{	"from":"Rocket Raccoon",	"stars":4,	"to":"Ronan",			"effect":"cr",	"value":7	},
{	"from":"Rocket Raccoon",	"stars":4,	"to":"Star-Lord",		"effect":"ar",	"value":6	},
{	"from":"Rocket Raccoon",	"stars":4,	"to":"Gamora",			"effect":"pbc",	"value":5	},
{	"from":"Rocket Raccoon",	"stars":4,	"to":"Drax",			"effect":"pbc",	"value":5	},
{	"from":"Ronan",				"stars":4,	"to":"Iron Man",		"effect":"cr",	"value":7	},
{	"from":"Ronan",				"stars":4,	"to":"Black Bolt",		"effect":"cd",	"value":25	},
{	"from":"Ronan",				"stars":4,	"to":"Gamora",			"effect":"cd",	"value":25	},
{	"from":"Scarlet Witch",		"stars":4,	"to":"Captain Marvel",	"effect":"ar",	"value":6	},
{	"from":"Scarlet Witch",		"stars":4,	"to":"Vision",			"effect":"pg",	"value":5	},
{	"from":"Spider-Man",		"stars":4,	"to":"Hawkeye",			"effect":"at",	"value":5	},
{	"from":"Spider-Man",		"stars":4,	"to":"Electro",			"effect":"cr",	"value":7	},
{	"from":"Spider-Man",		"stars":4,	"to":"Wolverine",		"effect":"h",	"value":6	},
{	"from":"Spider-Man",		"stars":4,	"to":"Captain America",	"effect":"ar",	"value":6	},
{	"from":"Star-Lord",			"stars":4,	"to":"Rocket Raccoon",	"effect":"ar",	"value":6	},
{	"from":"Star-Lord",			"stars":4,	"to":"Drax",			"effect":"pbc",	"value":5	},
{	"from":"Star-Lord",			"stars":4,	"to":"Gamora",			"effect":"pbc",	"value":5	},
{	"from":"Storm",				"stars":4,	"to":"Magik",			"effect":"ar",	"value":7	},
{	"from":"Storm",				"stars":4,	"to":"Black Panther",	"effect":"pg",	"value":5	},
{	"from":"Storm",				"stars":4,	"to":"Cyclops",			"effect":"pbc",	"value":5	},
{	"from":"Storm",				"stars":4,	"to":"Magneto",			"effect":"cr",	"value":7	},
{	"from":"Super. Iron Man",	"stars":4,	"to":"Captain America",	"effect":"cr",	"value":7	},
{	"from":"Super. Iron Man",	"stars":4,	"to":"Daredevil",		"effect":"cd",	"value":25	},
{	"from":"Super. Iron Man",	"stars":4,	"to":"Thor",			"effect":"pbc",	"value":5	},
{	"from":"The Vision",		"stars":4,	"to":"Iron Man",		"effect":"h",	"value":6	},
{	"from":"The Vision",		"stars":4,	"to":"Scarlet Witch",	"effect":"pbc",	"value":5	},
{	"from":"The Vision",		"stars":4,	"to":"Ultron Prime",	"effect":"at",	"value":5	},
{	"from":"Thor",				"stars":4,	"to":"Dr. Strange",		"effect":"ar",	"value":6	},
{	"from":"Thor",				"stars":4,	"to":"Iron Man",		"effect":"ar",	"value":6	},
{	"from":"Thor",				"stars":4,	"to":"Juggernaut",		"effect":"cr",	"value":7	},
{	"from":"Ultron Prime",		"stars":4,	"to":"Iron Man",		"effect":"h",	"value":6	},
{	"from":"Ultron Prime",		"stars":4,	"to":"Scarlet Witch",	"effect":"ar",	"value":6	},
{	"from":"Unst. Colossus",	"stars":4,	"to":"Wolverine",		"effect":"ar",	"value":6	},
{	"from":"Unst. Colossus",	"stars":4,	"to":"Magik",			"effect":"h",	"value":6	},
{	"from":"Unst. Colossus",	"stars":4,	"to":"Cyclops",			"effect":"pbc",	"value":5	},
{	"from":"Unst. Colossus",	"stars":4,	"to":"Juggernaut",		"effect":"cd",	"value":25	},
{	"from":"Vision",			"stars":4,	"to":"Scarlet Witch",	"effect":"pg",	"value":5	},
{	"from":"Vision",			"stars":4,	"to":"Iron Man",		"effect":"pbc",	"value":5	},
{	"from":"War Machine",		"stars":4,	"to":"Hulkbuster",		"effect":"ar",	"value":6	},
{	"from":"War Machine",		"stars":4,	"to":"Black Panther",	"effect":"cr",	"value":7	},
{	"from":"War Machine",		"stars":4,	"to":"Hawkeye",			"effect":"bp",	"value":20	},
{	"from":"War Machine",		"stars":4,	"to":"Black Widow",		"effect":"pbc",	"value":5	},
{	"from":"Winter Soldier",	"stars":4,	"to":"Wolverine",		"effect":"ar",	"value":6	},
{	"from":"Winter Soldier",	"stars":4,	"to":"Captain America",	"effect":"pbc",	"value":5	},
{	"from":"Wolverine",			"stars":4,	"to":"Captain America",	"effect":"ar",	"value":6	},
{	"from":"Wolverine",			"stars":4,	"to":"Cyclops",			"effect":"cd",	"value":25	},
{	"from":"Wolverine",			"stars":4,	"to":"Magneto",			"effect":"cr",	"value":7	},
{	"from":"Yellowjacket",		"stars":4,	"to":"Ant-Man",			"effect":"at",	"value":6	}
]);
